### ISSUE TITLE
Incompatible with Google Authenticator Plugin?

### ISSUE THREAD

**Issue by Anonymousdog** [wilminator/dokuwiki-plugin-twofactorsmsgateway#1]
HI, I find that, when GA extension is also enabled, that, even if the GA MFA method is not setup for a given user, and, even if that user has setup MFA via SMS, login does not require entering the an MFA code (at all).  Only if one manually adds "?do=twofactor_profile" to the URL does the wiki redirect to "?do=twofactor_login" upon which point the SMS is sent and demanded.

Running on 2017-02-19 "Frusterick Manners"  over Ubuntu 14.04, Apache 2.4.7 with just a few dokuwiki plugins (none of which involve authentication).

Thanks,
Andy

**Comment by wilminator** [comment]
Being able to skip GA in a multi-MFA environment is by design.  If you have both GA and another two factor method turned on, only one is required along with the user's password.  So, if a user had both GA and SMS setup, the user has the option to either supply the password and a GA code, or to supply a password and then the SMS code.  If the user supplies the password and GA token, then an SMS challenge will not be sent.

Assuming your case that the user has SMS configured but not GA, the GA code will not work and therefore is not required.  Am I understanding your environment correctly?

Also, I want to confirm that you are not bypassing the need to supply your account's password.

Thanks,
Mike

**Comment by Anonymousdog** [comment]
It's not working that way.

If I have both enabled and SMS configured on the account, as long as Google
Auth is globally enabled, I can skip MFA altogether.  It never, under no
conditions, redirects me to the two-factor login page.

Specifically, the password then SMS code doesn't work because dokuwiki
never requests the SMS code; it just gives me access to the site.

Not even sure how I'd bypass the account password; so, no.

Thanks,
Andy

**Comment by wilminator** [comment]
I apologize if I sound like I'm repeating myself, but I'm trying to understand the order of what you are seeing so I can replicate your problem on my computer.

My assumptions:
You have installed Attribute, Twofactor, Twofactorgoogleauth, and Towfactorsmsgateway.
You have turned on Twofactor, Twofactorgoogleauth, and Twofactorsmsgateway in the configuration editor.
Your account has enabled both GA and SMS.  
You have successfully confirmed both GA and SMS authentication for your user account and your Two Factor settings no longer are prompting for a confirmation code.

Your problem:
You login with only your username and your password.  You supply no GA code.
You are not prompted for an SMS code.  You are sent directly to your site's content.

Please let me know if I have everything right.

Thanks,
Mike

**Comment by wilminator** [comment]
I can replicate your problem in my test environment.  Thanks for the heads up.

**Comment by wilminator** [comment]
OK, let's see how this works...
The flaw is in the core twofactor module.  It fails to check if the user needs TFA for sites that do not have mandatory TFA turned on.

I have uploaded a new action.php file in the dev branch.  This works on my box; I'd like to confirm that it works for you before releasing it to the public.  The direct link is [twofactor/dev/action.php](https://github.com/wilminator/dokuwiki-plugin-twofactor/blob/dev/action.php)  If you would, please replace the dokuwiki/lib/plugins/twofactor/action.php file with the one I linked and let me know if it works for you.

Thanks,
Mike

**Comment by Anonymousdog** [comment]
Correct.  The GA option doesn't even have to be configured or active for
the user account.  Simply having the plugin enabled seems to break the
redirection to the two factor login page.

Andy

**Comment by Anonymousdog** [comment]
Sorry.  I missed that you had moved on...lol


I'll try the patched file and get back.

Thanks,
Andy

**Comment by Anonymousdog** [comment]
Most awesome.  When GA is configured for the user but SMS is not (but
enabled in wiki settings), and GA code is not entered, it now redirects to
a page that insists on the token.  When both are configured for the user,
failure to enter GA code redirects to a page requesting SMS code which is
dutifully sent.  Exactly as documented.

Can I also get you to add:
<code>
Google (project Fi)@msg.fi.google.com
</code>
to /twofactorsmsgateway/gateway.txt?  Nice job keeping the syntax in that
file dead simple, BTW.

Thanks,
Andy

**Comment by wilminator** [comment]
Thanks for the feedback.  I will promote the change to public.

That's a reasonable add to the file.  I kept it that way so you could add your own, but anything with Google's reach is probably a good add.  I will have to rework the code a little though- I never considered updating the file on my end and pushing this update out will clobber it.  I'll work in a local options file that the server will not overwrite on upgrades.  That may be a little while.

Happy trails,
Mike

**Comment by wilminator** [comment]
Adding this was much easier than I thought.  I have added Google's Project Fi to the list of gateways and added an override file so custom changes won't be blown out in the future.  That change is public.
